/*
 * generated by Xtext 2.20.0
 */
package fr.eseo.idm.state_machine_code_generator.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StateMachineCodeGeneratorUiModule extends AbstractStateMachineCodeGeneratorUiModule {

	public StateMachineCodeGeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
