/*
 * generated by Xtext 2.20.0
 */
package fr.eseo.idm.state_machine_code_generator.language;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StateMachineCodeGeneratorRuntimeModule extends AbstractStateMachineCodeGeneratorRuntimeModule {
}
