grammar fr.eseo.idm.state_machine_code_generator.language.StateMachineCodeGenerator
with org.eclipse.xtext.common.Terminals

import "http://eseo.fr/stateMachineCodeGenerator"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

StateMachine:
    (elements+=Element)*;

Element:
    State | Transition;

State:
    'state' name=ID '\n';

Event:
    name=ID;

Action:
    name=ID;

Transition:
    states+=[State] '->' states+=[State] ':' event=Event '/' (action=Action)? '\n';
