/*
 * generated by Xtext 2.20.0
 */
package fr.eseo.idm.state_machine_code_generator.language.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class StateMachineCodeGeneratorScopeProvider extends AbstractStateMachineCodeGeneratorScopeProvider {

}
