/*
 * generated by Xtext 2.20.0
 */
package fr.eseo.idm.state_machine_code_generator.language.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class StateMachineCodeGeneratorProposalProvider extends AbstractStateMachineCodeGeneratorProposalProvider {
}
