/*
 * generated by Xtext 2.20.0
 */
package fr.eseo.idm.state_machine_code_generator.language.ide;


/**
 * Use this class to register ide components.
 */
public class StateMachineCodeGeneratorIdeModule extends AbstractStateMachineCodeGeneratorIdeModule {
}
